services:
  web:
    build:
      context: ./src/
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "7001:7001"
    volumes:
      - "./src/:/app"
    environment:
      - ENV=${ENV}
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB=${MONGO_DB}
    networks:
      - app-networks
    # depends_on: Quitarlo para usar Atlas
    #   - mongo

  # Base local
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER_LOCAL:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD_LOCAL:-admin123}
      - MONGO_INITDB_DATABASE=${MONGO_DB_LOCAL:-pm_proyect}
    volumes:
      - mongo-data:/data/db
    networks:
      - app-networks

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER_LOCAL:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD_LOCAL:-admin123}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongo
    networks:
      - app-networks
    
  
  grafana:
    image: grafana/grafana-oss:latest  
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - app-networks
    depends_on:
      - mongo   

volumes:
  mongo-data:
  grafana-storage:
networks:
  app-networks:
    driver: bridge
